[package]
distribution = "2201.13.4"
org = "ballerinax"
name = "microsoft.outlook.calendar"
version = "3.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Vendor/Microsoft", "Area/Productivity & Collaboration", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.outlook.calendar"

[build-options]
observabilityIncluded = true
